#!/bin/bash
# ---------------------------------------------------------------
# scripts/instructor-setup-student-tokens.sh
#
# Run this ONCE before the lab starts.
# Creates a read-only Vault policy and 15 scoped student tokens.
#
# Prerequisites:
#   - VAULT_ADDR set (or vault already configured)
#   - VAULT_NAMESPACE=admin
#   - A Vault token with policy/token write permissions (admin)
#
# What it does:
#   1. Creates policy  : lab3931-student-readonly
#   2. Creates tokens  : one per student (lab3931-s01 … lab3931-s15)
#      - TTL: 8h (covers the full lab day with buffer)
#      - Policies: lab3931-student-readonly only
#      - Read-only: kv/data/IBM_cloud and kv/data/Packer
#   3. Writes tokens to: student-tokens/student-sNN.env
#      (distribute each file to the matching student)
#
# Usage:
#   export VAULT_ADDR="https://vault-cluster-3931-public-vault-0d5d4e35.e84a65be.z1.hashicorp.cloud:8200"
#   export VAULT_NAMESPACE="admin"
#   export VAULT_TOKEN="<your-admin-token>"
#   bash scripts/instructor-setup-student-tokens.sh
# ---------------------------------------------------------------

set -euo pipefail

BOLD="\033[1m"; GREEN="\033[1;32m"; CYAN="\033[1;36m"
YELLOW="\033[1;33m"; RED="\033[1;31m"; RESET="\033[0m"

ok()   { printf "  ${GREEN}✔  %s${RESET}\n" "$1"; }
info() { printf "  ${CYAN}▶  %s${RESET}\n" "$1"; }
warn() { printf "  ${YELLOW}⚠  %s${RESET}\n" "$1"; }
err()  { printf "  ${RED}✘  %s${RESET}\n" "$1"; }

VAULT_ADDR="${VAULT_ADDR:-https://vault-cluster-public-vault-564045ad.ea599dfb.z1.hashicorp.cloud:8200}"
VAULT_NAMESPACE="${VAULT_NAMESPACE:-admin}"
TOKEN_TTL="8h"
NUM_STUDENTS=1
OUTPUT_DIR="student-tokens"

printf "\n${BOLD}${CYAN}══════════════════════════════════════════════════════${RESET}\n"
printf "${BOLD}  LAB-3931 — Instructor: Create Student Vault Tokens${RESET}\n"
printf "${BOLD}${CYAN}══════════════════════════════════════════════════════${RESET}\n\n"

# ── Preflight checks ──────────────────────────────────────────
if [ -z "${VAULT_TOKEN:-}" ]; then
  err "VAULT_TOKEN is not set. Export your admin Vault token first:"
  printf "    export VAULT_TOKEN=\"<your-admin-token>\"\n\n"
  exit 1
fi

info "Vault address  : ${VAULT_ADDR}"
info "Vault namespace: ${VAULT_NAMESPACE}"
info "Token TTL      : ${TOKEN_TTL}"
info "Students       : ${NUM_STUDENTS}"
printf "\n"

# ── Step 1: Create the student read-only policy ───────────────
info "Creating Vault policy: lab3931-student-readonly ..."

POLICY_HCL=$(cat <<'POLICY'
# LAB-3931 student read-only policy
# Allows reading IBM Cloud credentials and HCP Packer credentials only.
# No write, no delete, no admin access.

path "kv/data/IBM_cloud" {
  capabilities = ["read"]
}

path "kv/metadata/IBM_cloud" {
  capabilities = ["read"]
}

path "kv/data/Packer" {
  capabilities = ["read"]
}

path "kv/metadata/Packer" {
  capabilities = ["read"]
}
POLICY
)

vault policy write \
  -namespace="${VAULT_NAMESPACE}" \
  lab3931-student-readonly \
  - <<< "${POLICY_HCL}" > /dev/null

ok "Policy lab3931-student-readonly created"
printf "\n"

# ── Step 2: Create student-tokens directory ───────────────────
mkdir -p "${OUTPUT_DIR}"
info "Token files will be written to: ${OUTPUT_DIR}/"
printf "\n"

# ── Step 3: Create one token per student ─────────────────────
info "Creating ${NUM_STUDENTS} student tokens..."
printf "\n"

for i in $(seq -w 1 ${NUM_STUDENTS}); do
  STUDENT_ID="s${i}"
  TOKEN_DISPLAY_NAME="lab3931-${STUDENT_ID}"
  OUTPUT_FILE="${OUTPUT_DIR}/student-${STUDENT_ID}.env"

  # Create the scoped token
  TOKEN_RESPONSE=$(vault token create \
    -namespace="${VAULT_NAMESPACE}" \
    -display-name="${TOKEN_DISPLAY_NAME}" \
    -policy="lab3931-student-readonly" \
    -ttl="${TOKEN_TTL}" \
    -metadata="student=${STUDENT_ID}" \
    -metadata="lab=lab3931" \
    -format=json 2>/dev/null)

  STUDENT_TOKEN=$(echo "${TOKEN_RESPONSE}" | jq -r '.auth.client_token')

  if [ -z "${STUDENT_TOKEN}" ] || [ "${STUDENT_TOKEN}" = "null" ]; then
    err "Failed to create token for ${STUDENT_ID}"
    continue
  fi

  # Write the env file for this student
  cat > "${OUTPUT_FILE}" <<ENV
# ---------------------------------------------------------------
# LAB-3931 Student Environment — ${STUDENT_ID}
# This file is generated by the instructor. Do not share it with
# other students. Token expires in ${TOKEN_TTL} from creation.
#
# Usage: source this file before running the lab setup script:
#   source student-tokens/student-${STUDENT_ID}.env
# ---------------------------------------------------------------

export VAULT_ADDR="${VAULT_ADDR}"
export VAULT_NAMESPACE="${VAULT_NAMESPACE}"
export VAULT_TOKEN="${STUDENT_TOKEN}"
export LAB_STUDENT_ID="${STUDENT_ID}"
ENV

  # Secure the file — only readable by owner
  chmod 600 "${OUTPUT_FILE}"

  ok "Student ${STUDENT_ID}: token written to ${OUTPUT_FILE}"
done

# ── Summary ────────────────────────────────────────────────────
printf "\n${BOLD}${GREEN}══════════════════════════════════════════════════════${RESET}\n"
printf "${BOLD}${GREEN}  Done! ${NUM_STUDENTS} student token files created.${RESET}\n"
printf "${BOLD}${GREEN}══════════════════════════════════════════════════════${RESET}\n\n"

printf "  Next steps:\n"
printf "  1. Distribute each file to the matching student:\n"
printf "       ${CYAN}student-tokens/student-s01.env${RESET} → Student 1\n"
printf "       ${CYAN}student-tokens/student-s02.env${RESET} → Student 2  ... etc\n\n"
printf "  2. Tell students to run:\n"
printf "       ${CYAN}source student-tokens/student-sNN.env${RESET}\n"
printf "       ${CYAN}bash scripts/student-setup-env.sh${RESET}\n\n"
printf "  3. After the lab, revoke all tokens at once:\n"
printf "       ${CYAN}bash scripts/instructor-revoke-student-tokens.sh${RESET}\n\n"

printf "  ${YELLOW}⚠  Keep student-tokens/ out of git — it is in .gitignore${RESET}\n\n"
